server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: session_selection
    static_configs:
    - targets:
        - localhost
      labels:
        job: session_selection
        __path__: /shared/session_selection.log