"""list_models

Revision ID: 026ed9e287d0
Revises: c0ae8aa27cd9
Create Date: 2020-08-05 10:16:02.689921

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '026ed9e287d0'
down_revision = 'c0ae8aa27cd9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pava_model',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('list_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('date_created', postgresql.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['list_id'], ['pava_list.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pava_model_session',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('model_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('session_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.ForeignKeyConstraint(['model_id'], ['pava_model.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['pava_session.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('pava_list', sa.Column('current_model_id', postgresql.UUID(as_uuid=True), nullable=True))
    op.create_foreign_key('fk_current_model_id', 'pava_list', 'pava_model', ['current_model_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_current_model_id', 'pava_list', type_='foreignkey')
    op.drop_column('pava_list', 'current_model_id')
    op.drop_table('pava_model_session')
    op.drop_table('pava_model')
    # ### end Alembic commands ###
