"""initial

Revision ID: 67d661607756
Revises: 
Create Date: 2020-03-25 13:11:15.095323

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '67d661607756'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('config',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('frame_step', sa.Integer(), nullable=True),
    sa.Column('frames_per_second', sa.Integer(), nullable=True),
    sa.Column('delta_1', sa.Integer(), nullable=True),
    sa.Column('delta_2', sa.Integer(), nullable=True),
    sa.Column('dtw_top_n_tail', sa.Integer(), nullable=True),
    sa.Column('dtw_beam_width', sa.Integer(), nullable=True),
    sa.Column('dtw_distance_metric', sa.String(), nullable=True),
    sa.Column('dtw_transition_cost', sa.Float(), nullable=True),
    sa.Column('knn_type', sa.Integer(), nullable=True),
    sa.Column('knn_k', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sravi_phrase',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('phrase_set', sa.String(), nullable=True),
    sa.Column('phrase_set_id', sa.String(), nullable=True),
    sa.Column('content', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pava_user',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('config_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.ForeignKeyConstraint(['config_id'], ['config.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sravi_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('config_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.ForeignKeyConstraint(['config_id'], ['config.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pava_list',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('default', sa.Boolean(), nullable=True),
    sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['pava_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sravi_template',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=True),
    sa.Column('feature_type', sa.String(), nullable=True),
    sa.Column('blob', sa.PickleType(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('phrase_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['phrase_id'], ['sravi_phrase.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['sravi_user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('feature_type', 'user_id', 'session_id', 'phrase_id')
    )
    op.create_table('pava_phrase',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('content', sa.String(), nullable=True),
    sa.Column('list_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.ForeignKeyConstraint(['list_id'], ['pava_list.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pava_template',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=True),
    sa.Column('feature_type', sa.String(), nullable=True),
    sa.Column('blob', sa.PickleType(), nullable=True),
    sa.Column('phrase_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.ForeignKeyConstraint(['phrase_id'], ['pava_phrase.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    pass
