"""archived_list_and_phrase

Revision ID: 9d35ccaa50dc
Revises: 67d661607756
Create Date: 2020-03-25 19:37:22.593004

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d35ccaa50dc'
down_revision = '67d661607756'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pava_list', sa.Column('archived', sa.Boolean(), nullable=True))
    op.add_column('pava_phrase', sa.Column('archived', sa.Boolean(), nullable=True))
    op.execute('UPDATE pava_list SET archived=false;')
    op.execute('UPDATE pava_phrase SET archived=false;')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pava_phrase', 'archived')
    op.drop_column('pava_list', 'archived')
    # ### end Alembic commands ###
