"""phrase_and_session_dates

Revision ID: bef4a01f7293
Revises: 026ed9e287d0
Create Date: 2020-09-14 12:07:14.261685

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'bef4a01f7293'
down_revision = '026ed9e287d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # server_default used to create date values of existing records, normal default doesn't work
    op.add_column('pava_phrase', sa.Column('date_created', postgresql.TIMESTAMP(), server_default=sa.text('make_timestamp(2020, 1, 1, 0, 0, 0)'), nullable=True))
    op.add_column('pava_session', sa.Column('date_created', postgresql.TIMESTAMP(), server_default=sa.text('make_timestamp(2020, 1, 1, 0, 0, 0)'), nullable=True))
    op.alter_column('pava_phrase', 'date_created', server_default=None)
    op.alter_column('pava_session', 'date_created', server_default=None)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pava_session', 'date_created')
    op.drop_column('pava_phrase', 'date_created')
    # ### end Alembic commands ###
