"""list_sessions

Revision ID: c0ae8aa27cd9
Revises: 9d35ccaa50dc
Create Date: 2020-05-04 11:24:37.712805

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c0ae8aa27cd9'
down_revision = '9d35ccaa50dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pava_template', 'session_id')
    op.drop_column('pava_template', 'feature_type')

    op.create_table('pava_session',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('list_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('new', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['list_id'], ['pava_list.id'], ),
    sa.PrimaryKeyConstraint('id')
    )

    op.execute('ALTER TABLE pava_template ADD session_id UUID;')
    op.create_foreign_key('fk_session_id', 'pava_template', 'pava_session', ['session_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pava_template', sa.Column('feature_type', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint('fk_session_id', 'pava_template', type_='foreignkey')
    op.drop_table('pava_session')
    # ### end Alembic commands ###
