"""list_enum

Revision ID: d574c9edfe20
Revises: bef4a01f7293
Create Date: 2020-09-14 16:48:49.329549

"""
from alembic import op
from main.utils.enums import ListStatus
from main.utils.types import IntEnum
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd574c9edfe20'
down_revision = 'bef4a01f7293'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pava_list', sa.Column('status', IntEnum(ListStatus), nullable=True))
    op.execute('UPDATE pava_list SET status=CASE WHEN archived=true THEN 2 ELSE 1 END;')
    op.drop_column('pava_list', 'archived')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pava_list', sa.Column('archived', sa.Boolean(), nullable=True))
    op.execute('UPDATE pava_list SET archived=CASE WHEN status=2 THEN true ELSE false END;')
    op.drop_column('pava_list', 'status')
    # ### end Alembic commands ###
